In [ ]:
a=8
b=5


In [ ]:
print(a==b)

False


In [ ]:

for i in range(1, 11):
    print(i)



1
2
3
4
5
6
7
8
9
10


In [ ]:
num = int(input("34"))

if num % 2 == 0:
    print("Even")
else:
    print("Odd")


KeyboardInterrupt: Interrupted by user

In [5]:
x=8
"odd"if x%2==0 else "even"



'odd'

In [6]:
for i in range (1,9):
 if i == 5:
    break
 print(i)


1
2
3
4


In [24]:
for i in range(1, 6):
    if i == 3:
        break
    print(i)


1
2


In [31]:
for i in range (1,20,2):
   if i in [9,10,11]:
     continue
   print(i)

1
3
5
7
13
15
17
19


In [33]:
q=  [1,2,3,4,5,6]
5 in q 

True

In [29]:
for i in range (1,20):
   if i==7:
     continue
   print(i)

1
2
3
4
5
6
8
9
10
11
12
13
14
15
16
17
18
19


In [25]:
for i in range(1, 6):
    if i == 3:
        continue
    print(i)


1
2
4
5


In [16]:
for i in range(1, 6):
    if i == 3:
        continue
    print(i)


1
2
4
5


In [23]:
for i in range(1, 4):
    pass


In [26]:
for i in range(1, 6):
    if i == 3:
        pass
    print(i)


1
2
3
4
5


# Practice

In [34]:
x = 10
y = 20

if x < y:
    if y % 2 != 0:
        print("A")
    else:
        print("B")
else:
    print("C")


B


In [35]:
a = 5
b = 3
c = 7

if a > b and b > c:
    print("X")
elif a > b or b > c:
    if not (c < a):
        print("Y")
    else:
        print("Z")
else:
    print("W")


Y


In [36]:
x = 0

if x:
    print("True")
elif x == False:
    print("False")
else:
    print("Else")


False


In [37]:
print(5 + 2 * 3)

11


In [38]:
print(10 > 5 > 2)


True


In [39]:
x = 5
print(x == 5 or 6)

True


In [40]:
for i in range(2):
    for j in range(2):
        print(i, j)
 

0 0
0 1
1 0
1 1


In [44]:
for i in range(3):
    for j in range(i):
        print(f"{i+1} loop")
        print("Hello")


2 loop
Hello
3 loop
Hello
3 loop
Hello


In [45]:
for i in range(1):
    print(i)

0


In [46]:
for i in range(3):
    for j in range(2):
        if i == j:
            break
        print(i, j)


1 0
2 0
2 1


In [47]:
s = "python"
print(s[2])

t


In [48]:
s = "python"
print(s[-3])


h


In [49]:
s = "python"
print(s[1:5:2])


yh


In [51]:
for i in range(1,5):
    if i % 2 == 0:
        print(i * 2)


4
8


In [52]:
x = [1, 2, 3]

for i in x:
    if i == 2:
        continue
    print(i)


1
3


In [56]:
x = "abc"

for i in range(len(x)):
    if x[i] == "b":
        break
    print(x[i])


a


In [59]:
for i in range(3):
    for j in range(3):
        if i + j == 3:
            break
        print(i, j)


0 0
0 1
0 2
1 0
1 1
2 0


In [60]:
x = 0
y = 5

if x and y:
    print("A")
elif x or y:
    print("B")
else:
    print("C")


B


In [62]:
print(3 < 5 < 2)
print(3 < 5 > 2)


False
True


In [63]:
print(True + True * False)


1


In [65]:
for i in range(3):
    for j in range(3):
        if j == 1:
            break
        print(i, j)


0 0
1 0
2 0


In [67]:
for i in range(4):
    if i == 2:
        continue
    print(i)


0
1
3


In [68]:
s = "python"

for i in range(len(s)):
    if s[i] in "aeiou":
        print(i, s[i])


4 o


In [75]:
s = "abcdef"
print(s[4:1:-2])


ec


In [77]:
x = 1

for i in range(3):
    x += i

print(x)


4


In [78]:
for i in range(3):
    for j in range(3):
        if i == 1:
            continue
        if j == 2:
            break
        print(i, j)


0 0
0 1
2 0
2 1


In [81]:
for i in range(4, 0, -1):
    print("manu" * i)


manumanumanumanu
manumanumanu
manumanu
manu


In [94]:
numbers=[6,5,9,67,99]
for n in numbers:
    if n ==67:
        print("found it")
        break
else:
     print("not found it")

found it


In [95]:
numbers = [1, 2, 3, 4, 5]

for n in numbers:
    if n == 3:
        print("Found it")
        break
else:
    print("Not found it")


Found it


In [106]:
num = 7
if num > 1:
    for i in range(2,num):
        if num % i==0:
            print("not prime")
            break
    else:
        print("prime")
else:
    print("not prime")

prime


In [107]:
import array
    

In [114]:
from array import *

In [115]:
s = array('i',[4,56,78,4,3,56,])

print(s)

array('i', [4, 56, 78, 4, 3, 56])


In [132]:
num = 7

if num > 1:
    for i in range(2, num):
        if num % i == 0:
            print("Not Prime")
            break
    else:
        print("Prime")
else:
    print("Not Prime")


Prime


In [140]:
for i in range(2,3):
    for j in range(3,5):
        print(i)

         
 


2
2


In [141]:
k=2
while k<3:
    l=3
    while l<5:
        print(k)
        l=l+1
    k=k+1    


2
2


In [136]:
a=5
count=1
while count <=3:
   if a%2==0:
      a =a +2
   if a%3 == 0:
      a= a+3
   else:
      a=a+1
   count=count+1
print(a)


12


In [ ]:
from array import*

arr = array('i',[])
n


In [8]:
numbers = [1, 2, 3, 4]
print(numbers [0:2])

[1, 2]


In [9]:
for i in range(len(numbers)):  
    numbers[i] = numbers[i] * 2
    print(numbers[i])


2
4
6
8


In [6]:
import numpy as np

In [2]:
arr = np.array([1, 2, 3, 4])
print(arr * 2)


[2 4 6 8]


                  #ways of creating arrys in numpy

In [12]:
import numpy as  np

In [18]:
a = np.array({1,2,3,4})
print(a)

{1, 2, 3, 4}


In [19]:
b = np.array([[1,2,3], [4,5,6]])
print(b)


[[1 2 3]
 [4 5 6]]


In [65]:
a=np.array([14])
c=(a)
print(c)

[7]


3 x 1 = 3
3 x 2 = 6
3 x 3 = 9
3 x 4 = 12
3 x 5 = 15
3 x 6 = 18
3 x 7 = 21
3 x 8 = 24
3 x 9 = 27
3 x 10 = 30


In [76]:
import numpy as np

a = np.array([24])
c = np.array([a[0]//2, a[0]//2])
print(c)


[12 12]


In [90]:
import numpy as np
a= np.array([30])
b=np.array([a//15])
c=np.repeat(b , 15 )
print(c)

[2 2 2 2 2 2 2 2 2 2 2 2 2 2 2]


In [100]:
import numpy as np
a = np.array([28])
c= np.full(a//2 , 2)
print(c)

[2 2 2 2 2 2 2 2 2 2 2 2 2 2]


In [105]:
import numpy as np 

result =  30/3
arr = np.repeat(result, 7)
print(arr)

[10. 10. 10. 10. 10. 10. 10.]


In [108]:
import numpy as np

a = 28
b = 5

result = np.full(a // b, b)
print(result)


[5 5 5 5 5]


In [133]:
a = 28
b = 5

result = [b] * (a // b)

if a % b != 0:
    result.append(a % b)

print(result)
  


[5, 5, 5, 5, 5, 3]


In [124]:
a = 95
b = 6

quotient = a // b
remainder = a % b

result = [b] * quotient

if remainder != 0:
    result.append(remainder)
    print(result, "=", quotient, "+ 1")
else:
    print(result, "=", quotient)


[6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 5] = 15 + 1


In [132]:
a =95
b = 6

quotient = a // b
remainder = a % b

result = [b] * quotient

if remainder != 0:
    result.append(remainder)
    print(f"{result} = {b}*{quotient} + {remainder}*1 = {a}")
else:
    print(f"{result} = {b}*{quotient} = {a}")


[6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 5] = 6*15 + 5*1 = 95


In [134]:
a =95
b = 6

quotient = a // b
remainder = a % b

result = [b] * quotient

if remainder != 0:
    result.append(remainder)

In [ ]:
a = np.array({1, 2, 3, 4})
print(a)


[1 2 3 4]


In [139]:
np.zeros((2,3))


array([[0., 0., 0.],
       [0., 0., 0.]])

In [141]:
a=np.full(5, 7)
print(a)

[7 7 7 7 7]


In [145]:
a=np.linspace(0, 11, 5)
print(a)

[ 0.    2.75  5.5   8.25 11.  ]


In [179]:
a=np.random.rand(3)
b=np.random.randint(10,size= (5,5))  ################################################
print(a)
print(b)

[0.45358433 0.78129179 0.93289957]
[[5 3 4 6 0]
 [5 6 6 6 7]
 [8 5 0 3 5]
 [8 9 7 7 2]
 [2 8 2 2 1]]


In [ ]:
np.eye(5) 


array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [180]:
a=np.empty(3)
print(a)

[0.45358433 0.78129179 0.93289957]


In [156]:
import numpy as np

a = np.array([1, 2, 3])

b = a        # Not a real copy
b[0] = 100

print(b)     # Also changes!


[100   2   3]


In [160]:
import numpy as np
a=np.array([1, 2, 3])
b=a.copy()
b[0] = 100         
print(a)   
print(b)

[1 2 3]
[100   2   3]


In [181]:
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

print(A)


[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [184]:
print(A[0, 1])   # Row 0, Column 1

2


In [197]:
print(A[2])   


[7 8 9]


In [193]:
print(A[:, 2])   # Third column


[3 6 9]


In [238]:
A = np.array([[10, 8, 7],
              [6, 6,  4],
              [3, 2, 2]])

print(A)


[[10  8  7]
 [ 6  6  4]
 [ 3  2  2]]


In [240]:
B = np.array([[9, 8, 7],
              [6, 5, 4],
              [3, 2, 1]])

print(B)


[[9 8 7]
 [6 5 4]
 [3 2 1]]


In [241]:
print(np.dot(A, B))

[[159 134 109]
 [102  86  70]
 [ 45  38  31]]


In [242]:
print(A * B)


[[90 64 49]
 [36 30 16]
 [ 9  4  2]]


In [214]:
print(np.dot(A, B))


[[159 134 109]
 [102  86  70]
 [ 45  38  31]]


In [219]:
print(np.dot(A, B))


[[159 134 109]
 [102  86  70]
 [ 45  38  31]]


In [245]:
print(B.T)


[[9 6 3]
 [8 5 2]
 [7 4 1]]


In [221]:
A = np.array([[10, 8, 7],
              [6, 6,  4],
              [3, 2, 2]])

print(A)

[[10  8  7]
 [ 6  6  4]
 [ 3  2  2]]


In [222]:
print(A.T)

[[10  6  3]
 [ 8  6  2]
 [ 7  4  2]]


In [229]:
C = np.arange(12)
D = C.reshape(3, 4)

print(D)


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [223]:
A = np.array([[10, 8, 7],
              [6, 6,  4],
              [3, 2, 2]])

print(A)

[[10  8  7]
 [ 6  6  4]
 [ 3  2  2]]


In [230]:
print(A.flatten())


[10  8  7  6  6  4  3  2  2]


In [231]:
print(np.linalg.det(A))


-2.0000000000000133


In [232]:
print(np.linalg.inv(A))


[[-2.00000000e+00  1.00000000e+00  5.00000000e+00]
 [-6.47630098e-16  5.00000000e-01 -1.00000000e+00]
 [ 3.00000000e+00 -2.00000000e+00 -6.00000000e+00]]


FUNCTIONS

In [ ]:
def greet(name, x, y):
    print(f"Hello, welcome {name}")  
    print(x*y)
    #print("how r u toda")
greet("manu",3,4)

Hello, welcome manu
12


In [258]:
def hii(location, x,y):
    print(f"I am going to {location}")
    print(f"my budget is {x*y}")
hii("Goa",50,45)


I am going to Goa
my budget is 2250


In [260]:
def add (a,b):
    print(a+b)
add(5,3)


8


In [ ]:
def add(a,b):
     c = a+b
     return(c, type(c))

In [279]:
x = 10

def change():
    global x
    x = 20   # This creates a new local variable

change()
print(x)


20


In [282]:
total = 0

def add(value):
    global total
    total += value

add(5)
add(10)

print(total)



15


In [269]:
def add(a,b):
     c = a+b
     print(c, type(c))

In [270]:
add(56,64)

120 <class 'int'>


# doubts

In [224]:
a=np.empty(3)     ######################################
print(a)

[0.45358433 0.78129179 0.93289957]


In [225]:
a=np.random.rand(3)
b=np.random.randint(1, 10, 5)  ################################################
print(a)
print(b)

[0.9705602  0.38335831 0.17048016]
[2 6 2 3 7]


In [226]:
count = 0
            #########################################################
for i in range(3):
    for j in range(3):
        if count== -2:
            break
        else:
            if i == j:
                count += 1
            else:
                count -= 1

print(count)


-2


In [227]:
for i in range(3):
    for j in range(3):
        if j == 1:
            break
        print(i, j)

0 0
1 0
2 0


In [228]:
s = "abcdef"    ########################################
print(s[5:1:-2])

fd


#Arguments

In [ ]:
def add(a, b):
    print(a + b)

add(2, 3)   # 2 and 3 are positional arguments